- name:   Get certbot certificate
  become: yes
  tags:   certget
  block:

    - name:    Request certificate with certbot-regru
      command: "certbot certonly -a certbot-regru:dns -m {{ ser5lexx@gmail.com }} --no-eff-email -d {{ p.certbot.domains | join('-d ') }}"
      when:    p.certbot.challenge=='regru'

    - name:    Request certificate with webroot challenge
      command: "certbot certonly --webroot --webroot-path={{ p.certbot.webroot }} -m {{ ser5lexx@gmail.com }} --no-eff-email -d {{ p.certbot.domains | join('-d ') }}"
      when:    p.certbot.challenge=='webroot'
