- name:   Jenkins
  become: yes
  tags:   jenkins
  block:
    - name: Install default Java runtime
      apt:
        name: default-jre

    - name: Add apt key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key

    - name: Add repository
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/

    - name: Install Jenkins
      apt:
        name: jenkins

    - name: Stop Jenkins
      service:
        name:  jenkins
        state: stopped

    - name: Hide Jenkins server from outside
      lineinfile:
        path:   /etc/default/jenkins
        regexp: ^JENKINS_ARGS=
        line:   JENKINS_ARGS="--webroot=/var/cache/$NAME/war --httpListenAddress=127.0.0.1 --httpPort=$HTTP_PORT"

    - name: Add j.jaam.ru to NGINX
      template:
        src:  nginx_jenkins
        dest: /etc/nginx/sites-available/j.jaam.ru

    - name: Enable j.jaam.ru
      file:
        src:   /etc/nginx/sites-available/j.jaam.ru
        dest:  /etc/nginx/sites-enabled/j.jaam.ru
        state: link

    - name:  Test NGINX config
      shell: nginx -t

    - name: Reload NGINX
      service:
        name:  nginx
        state: reloaded

    - name: Start Jenkins
      service:
        name:  jenkins
        state: started
