- name:   PHP
  become: yes
  tags:   php
  block:

    - name: Install PHP
      apt:
        name:  "php{{ p.php.version }}"
        state: present

    - name: Install PHP packages
      apt:
        name:  "php{{ p.php.version }}-{{ item }}"
        state: present
      loop: [
        mbstring, curl, gd, zip, intl, xml, xmlrpc,
        mysql, mongodb, redis,
        igbinary, gmp, xdebug,
        fpm
      ]

    - name: Install Composer
      apt:
        name:  composer
        state: present

    - name: Create custom PHP config
      template:
        src:  php.ini
        dest: /etc/php/custom.ini

    - name: Create dir for FPM pools
      file:
        path:  "/etc/php/{{ p.php.version }}/fpm/pool.d/"
        state: directory

    - name: Create symlinks to custom PHP config
      file:
        src:   /etc/php/custom.ini
        dest:  "/etc/php/{{ p.php.version }}/{{ item }}/conf.d/99-custom.ini"
        state: link
      loop: ['fpm', 'cli']

    - name: Copy php-fpm pool files
      template:
        src:  "{{ playbook_dir }}/host_templates/{{ item }}"
        dest: "/etc/php/{{ p.php.version }}/fpm/pool.d/{{ item }}"
      loop: "{{ p.php.fpm.pools }}"
      when: (p.php.fpm.pools | length>0)

    - name: Restart php-fpm
      service:
        name:  "php{{ p.php.version }}-fpm"
        state: restarted
