- name: Midnight Commander
  tags: mc
  block:
    - name:   Install MC
      become: yes
      apt:
        name:  mc
        state: present

    - name: 'Configure MC ini [mc]'
      ini_file:
        path:    ~/.config/mc/ini
        section: 'Midnight-Commander'
        option:  "{{ item.key }}"
        value:   "{{ item.value }}"
      loop: "{{ data | dict2items }}"
      vars:
        data:
          auto_save_setup:                    'true'
          use_internal_view:                  'true'
          editor_return_does_auto_indent:     'true'
          editor_fake_half_tabs:              'false'
          editor_cursor_after_inserted_block: 'true'
          editor_ask_filename_before_edit:    'true'

    - name: 'Configure MC ini [Panels]'
      ini_file:
        path:    ~/.config/mc/ini
        section: Panels
        option:  auto_save_setup_panels
        value:   'true'

    - name: Configure MC hotlist
      lineinfile:
        create: yes
        path:   ~/.config/mc/hotlist
        regexp: '^ENTRY "{{ item }}"'
        line:   'ENTRY "{{ item }}" URL "{{ item }}"'
      loop:
        - '/var/www/'
        - '/etc/'
        - '/etc/php/'
        - '/etc/apache2/'
        - '/etc/nginx/'
        - '/etc/mysql/'
        - '/etc/pure-ftpd/'
        - '/var/log/'
        - '/tmp/'
