- name:   Node.js
  become: yes
  tags:   nodejs
  block:
    - name: Install Node.js
      apt:
        name:  [nodejs, npm]
        state: present

    - name:    Update npm
      command: 'npm install npm@latest -g'
